# Starter

In [18]:
name = 'laura'
name

'laura'

In [15]:
name = 'laura'
name.capitalize()

'Laura'

In [19]:
name[0]

'l'

In [20]:
name[-1]

'a'

In [21]:
name[1:]

'aura'

In [22]:
name[::2]

'lua'

In [23]:
name*2

'lauralaura'

In [27]:
import pandas as pd

df = pd.read_csv('iris_dataset.csv')

df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [29]:
name.islower()

True

In [31]:
name = 'LAURA'

In [32]:
name.islower()

False

In [35]:
if name.isupper():
    print ('The name is uppercase')

The name is uppercase


In [37]:
if not name.isupper():
    print ('The name is not uppercase')
    print ('The name is lowercase')

In [38]:
ids = [1,2,3,4,5]
person_id = input ('Please enter your id: ')

if person_id in ids:
    print ('Welcome! ')
else:
    print ('Try again! ')

Please enter your id: 6
Try again! 


In [40]:
ids = [1,2,3,4,5]

while person_id not in ids:
    person_id = int(input('Please enter your id: '))

    if person_id in ids:
        print ('Welcome! ')
    else:
        print ('Try again! ')

Please enter your id: 6
Try again! 
Please enter your id: 3
Welcome! 


In [41]:
number = 0
while number < 4:
    print (number, 'is less than 4')
    number += 1


0 is less than 4
1 is less than 4
2 is less than 4
3 is less than 4


# Practical lab activity

In [43]:
ages = [90,92,94,95,96,97,98]
len(ages)

7

In [45]:
ages[0]

90

In [46]:
ages[6]

98

In [47]:
ages[3:]

[95, 96, 97, 98]

In [48]:
for item in ages:
    print(item)

90
92
94
95
96
97
98


In [53]:
ages.append(100)
ages

[90, 92, 94, 95, 96, 97, 98, 100]

## Dictionaries

In [60]:
books = {
    'title': 'Hamlet',
    'author': 'William Shakespeare',
    'language': 'English'
}

In [61]:
books['title']

'Hamlet'

In [62]:
books.keys()

dict_keys(['title', 'author', 'language'])

In [63]:
books.values()

dict_values(['Hamlet', 'William Shakespeare', 'English'])

In [66]:
books.items()

dict_items([('title', 'Hamlet'), ('author', 'William Shakespeare'), ('language', 'English')])

In [67]:
books = {
    'title': 'King Lear',
    'author': 'William Shakespeare',
    'language': 'English'
}

In [69]:
books['title']

'King Lear'

## Selection

In [70]:
age = int(input('Please enter your age: '))

Please enter your age: 31


In [71]:
if age >= 18:
    print ('You are in category A')

You are in category A


In [72]:
if age >= 16:
    print ('You are in category B')

You are in category B


In [73]:
if age < 16:
    print ('You are in category C')

In [74]:
if age >= 18:
    print ('You are in category A')
elif age >= 16:
    print ('You are in category B')
else:
    print ('You are in category C')

You are in category A


# Numpy

In [75]:
import numpy as np

In [76]:
payments = np.array([6.99, 12.40, 75.00, 1.55])

In [77]:
print(payments)

[ 6.99 12.4  75.    1.55]


In [78]:
payments

array([ 6.99, 12.4 , 75.  ,  1.55])

In [81]:
arr = np.array([3, 3, 5, 7, 9])

print(arr)

[3 3 5 7 9]


In [84]:
arr2 = np.array([[3, 3, 5, 7], [2, 4, 6, 8], [3, 4, 5, 6]])

print(arr2)

[[3 3 5 7]
 [2 4 6 8]
 [3 4 5 6]]


In [85]:
arr2.ndim

2

In [86]:
arr2.shape

(3, 4)

In [87]:
arr2.dtype

dtype('int32')