# Starter

In [18]:
name = 'laura'
name

'laura'

In [15]:
name = 'laura'
name.capitalize()

'Laura'

In [19]:
name[0]

'l'

In [20]:
name[-1]

'a'

In [21]:
name[1:]

'aura'

In [22]:
name[::2]

'lua'

In [23]:
name*2

'lauralaura'

In [27]:
import pandas as pd

df = pd.read_csv('iris_dataset.csv')

df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [29]:
name.islower()

True

In [31]:
name = 'LAURA'

In [32]:
name.islower()

False

In [35]:
if name.isupper():
    print ('The name is uppercase')

The name is uppercase


In [37]:
if not name.isupper():
    print ('The name is not uppercase')
    print ('The name is lowercase')

In [38]:
ids = [1,2,3,4,5]
person_id = input ('Please enter your id: ')

if person_id in ids:
    print ('Welcome! ')
else:
    print ('Try again! ')

Please enter your id: 6
Try again! 


In [40]:
ids = [1,2,3,4,5]

while person_id not in ids:
    person_id = int(input('Please enter your id: '))

    if person_id in ids:
        print ('Welcome! ')
    else:
        print ('Try again! ')

Please enter your id: 6
Try again! 
Please enter your id: 3
Welcome! 


In [41]:
number = 0
while number < 4:
    print (number, 'is less than 4')
    number += 1


0 is less than 4
1 is less than 4
2 is less than 4
3 is less than 4


# Practical lab activity

In [43]:
ages = [90,92,94,95,96,97,98]
len(ages)

7

In [45]:
ages[0]

90

In [46]:
ages[6]

98

In [47]:
ages[3:]

[95, 96, 97, 98]

In [48]:
for item in ages:
    print(item)

90
92
94
95
96
97
98


In [53]:
ages.append(100)
ages

[90, 92, 94, 95, 96, 97, 98, 100]

## Dictionaries

In [60]:
books = {
    'title': 'Hamlet',
    'author': 'William Shakespeare',
    'language': 'English'
}

In [61]:
books['title']

'Hamlet'

In [62]:
books.keys()

dict_keys(['title', 'author', 'language'])

In [63]:
books.values()

dict_values(['Hamlet', 'William Shakespeare', 'English'])

In [66]:
books.items()

dict_items([('title', 'Hamlet'), ('author', 'William Shakespeare'), ('language', 'English')])

In [67]:
books = {
    'title': 'King Lear',
    'author': 'William Shakespeare',
    'language': 'English'
}

In [69]:
books['title']

'King Lear'

## Selection

In [70]:
age = int(input('Please enter your age: '))

Please enter your age: 31


In [71]:
if age >= 18:
    print ('You are in category A')

You are in category A


In [72]:
if age >= 16:
    print ('You are in category B')

You are in category B


In [73]:
if age < 16:
    print ('You are in category C')

In [74]:
if age >= 18:
    print ('You are in category A')
elif age >= 16:
    print ('You are in category B')
else:
    print ('You are in category C')

You are in category A


# Numpy

## Practical activity

In [10]:
import numpy as np

x = np.arange(10)
y = np.array([[12, 5, 2, 4],
               [7, 6, 8, 8],
               [1, 6, 7, 7]])

In [12]:
first_5_elements = x[:5]
print('first_5_elements of x:', first_5_elements)

first_5_elements of x: [0 1 2 3 4]


In [13]:
first_column = y[:,0]
print('first column of y:', first_column)

first column of y: [12  7  1]


In [14]:
first_row = y[0,:]
print('first row of y:', first_row)

first row of y: [12  5  2  4]


In [15]:
z = np.array([1, 2, 3, 4])

z_column = z.reshape(-1, 1)

print('Original row (z):')
print(z)
print('\nTransposed column (z_column):')
print(z_column)

Original row (z):
[1 2 3 4]

Transposed column (z_column):
[[1]
 [2]
 [3]
 [4]]


In [16]:
z_column.reshape(1,-1)

array([[1, 2, 3, 4]])

## Practical lab

In [12]:
import pandas as pd

In [13]:
import numpy as np

In [19]:
df1 = pd.read_csv('Data/mortgage_applicants.csv')

In [21]:
df2 = pd.read_excel('Data/mortgage_applicants.xlsx')

In [23]:
df3 = pd.read_json('Data/weather.json', orient = 'split')

In [24]:
df1

Unnamed: 0   ID  Income      Term  Balance  Debt  Score  Default
0             0  567   17626  10 Years     1381   293  228.0    False
1             1  523   18959  20 Years      883  1012  187.0    False
2             2  544   20560  10 Years      684   898   86.0    False
3             3  370   21894  10 Years      748    85    NaN    False
4             4  756   24430  10 Years     1224    59  504.0    False
..          ...  ...     ...       ...      ...   ...    ...      ...
851         851   71   30191  20 Years     1319  3880   55.0     True
852         852  932   41669  20 Years     1385    32  780.0    False
853         853   39   36816  20 Years     1868  3123  366.0     True
854         854  283   42145  20 Years     1447  2498  422.0    False
855         855  847   30594  20 Years     1216  2473  179.0     True

[856 rows x 8 columns]

In [25]:
df2

Unnamed: 0   ID  Income      Term  Balance  Debt  Score  Default
0             0  567   17626  10 Years     1381   293  228.0    False
1             1  523   18959  20 Years      883  1012  187.0    False
2             2  544   20560  10 Years      684   898   86.0    False
3             3  370   21894  10 Years      748    85    NaN    False
4             4  756   24430  10 Years     1224    59  504.0    False
..          ...  ...     ...       ...      ...   ...    ...      ...
851         851   71   30191  20 Years     1319  3880   55.0     True
852         852  932   41669  20 Years     1385    32  780.0    False
853         853   39   36816  20 Years     1868  3123  366.0     True
854         854  283   42145  20 Years     1447  2498  422.0    False
855         855  847   30594  20 Years     1216  2473  179.0     True

[856 rows x 8 columns]

In [26]:
df3

temp  humidity  sun_hrs
2023-07-15  15.68     73.18     6.40
2023-07-16  25.16     83.88     8.06
2023-07-17  13.26     80.05     4.89
2023-07-18  24.63     82.37     9.13
2023-07-19  12.78     83.10    17.10
2023-07-20  23.52     85.35     0.72
2023-07-21  17.80     85.64     5.79
2023-07-22  24.98     76.81    10.95
2023-07-23  23.48     80.86     3.77
2023-07-24  23.30     79.96    14.62